### PR TITLE
added installation of pip3 to bootstrap.sh

### LINKED ISSUE #36: Add pip3 installation to bootstrap.sh

### PR DESCRIPTION
**Pull request by IlanZuckerman**
fix #36

### CODE REVIEW

**Comment by IlanZuckerman** [comment]
> Have you tried to run it?

Probably not good enough :)
Needed to add -y to make the command un-attended. Requested a new Pull request.

**Comment by lioramilbaum** [comment]
Can you verify why the CI didn't pick up the problem?

**Comment by IlanZuckerman** [comment]
> Can you verify why the CI didn't pick up the problem?

Thats weird. looking at raw logs of the CI i can see that the package was installed although it wasnt passed with -y.
https://travis-ci.org/IlanZuckerman/baboon/builds/651959361

`Selecting previously unselected package python3-pip.
Preparing to unpack .../python3-pip_9.0.1-2.3~ubuntu1.18.04.1_all.deb ...
Unpacking python3-pip (9.0.1-2.3~ubuntu1.18.04.1) ...
Setting up python-pip-whl (9.0.1-2.3~ubuntu1.18.04.1) ...
Setting up python3-pip (9.0.1-2.3~ubuntu1.18.04.1) ...`

**Comment by lioramilbaum** [comment]
Can you ask a question in the travis community?
https://travis-ci.community/

I will merge the PR, but we should watch out for those cases. Would suggest to file a new issue and track that till we figure out why CI didn't fail.

**Comment by IlanZuckerman** [comment]
> Can you ask a question in the travis community?
> https://travis-ci.community/
> 
> I will merge the PR, but we should watch out for those cases. Would suggest to file a new issue and track that till we figure out why CI didn't fail.

Opened a ticket for Travis community:
https://travis-ci.community/t/provisioning-ubuntu-vm-through-ci-doesnt-fail-when-provision-script-has-command-which-is-not-unattended-y/7276

**Comment by lioramilbaum** [comment]
@IlanZuckerman You might want to file one in this repo to enable others to track the outcome

**Comment by IlanZuckerman** [comment]
> @IlanZuckerman You might want to file one in this repo to enable others to track the outcome

Thanks. done.

**Pull request merged**
